<a href="https://colab.research.google.com/github/AnupamaRajkumar/PyTorchTutorials/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install torch

In [3]:
import torch
import numpy as np

In [5]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [6]:
def forward(x):
   y = w*x + b
   return y

In [8]:
x = torch.tensor([[4], [7]])
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

Linear Regression

In [9]:
from torch.nn import Linear

In [10]:
#random initialisation 
torch.manual_seed(1)
#creating a linear model
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [12]:
x = torch.tensor(([2.0], [3.3]))
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)


Custom Modules