<a href="https://colab.research.google.com/github/AnupamaRajkumar/PyTorchTutorials/blob/main/NumPyFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.learnthepart.com/

Arrays vs List

In [1]:
import numpy as np

With python list

In [5]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for index in range(3):
  list_two[index] = list_two[index] ** 2
  list_three[index] = list_three[index] ** 3
  list_sum.append(list_two[index] + list_three[index])

print(list_sum)


[2, 12, 36]


With numpy instead\
Range in list creates a list in the range and arange in array creates an array in range\
range -> list\
arange -> array

In [7]:
#array allows us to perform vectorised operations easily which is not possible with list
array_two = np.arange(1, 4) ** 2
array_three = np.arange(1, 4) ** 3
#direct addition of lists would lead to lists being concatenated
print(array_two + array_three)

[ 2 12 36]


Common mathematical operations accessible through numpy

In [12]:
sample_array = np.array([1, 2, 3])

In [13]:
np.power(sample_array, 4)
#this can also be written as np.array([1, 2, 3]) ** 4

array([ 1, 16, 81])

In [15]:
print(np.negative(sample_array))

[-1 -2 -3]


In [16]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [17]:
#natural log
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

numpy arrays have more efficient memory consumption and are faster as compared to their python list counterparts

In [18]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

#Multidimensional array
An n-dimensional array is homogeneous ie each element in array with take same amount of space in memory

In [23]:
x = np.arange(0, 3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [24]:
multi_array[1, 2]

5

In [22]:
#50 represents the number of equally spaced points between 1 and 10
#If false value up to 10 not included
w = np.linspace(1, 10, 50, False)
print(w)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


In [ ]:
#3 represents stepsize
w = np.arange(1, 30, 3)