<a href="https://colab.research.google.com/github/AnupamaRajkumar/PyTorchTutorials/blob/main/NumPyFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.learnthepart.com/

Arrays vs List

In [2]:
import numpy as np

With python list

In [ ]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for index in range(3):
  list_two[index] = list_two[index] ** 2
  list_three[index] = list_three[index] ** 3
  list_sum.append(list_two[index] + list_three[index])

print(list_sum)


[2, 12, 36]


With numpy instead\
Range in list creates a list in the range and arange in array creates an array in range\
range -> list\
arange -> array

In [ ]:
#array allows us to perform vectorised operations easily which is not possible with list
array_two = np.arange(1, 4) ** 2
array_three = np.arange(1, 4) ** 3
#direct addition of lists would lead to lists being concatenated
print(array_two + array_three)

[ 2 12 36]


Common mathematical operations accessible through numpy

In [ ]:
sample_array = np.array([1, 2, 3])

In [ ]:
np.power(sample_array, 4)
#this can also be written as np.array([1, 2, 3]) ** 4

array([ 1, 16, 81])

In [ ]:
print(np.negative(sample_array))

[-1 -2 -3]


In [ ]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#natural log
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

numpy arrays have more efficient memory consumption and are faster as compared to their python list counterparts

In [ ]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

#Multidimensional array
An n-dimensional array is homogeneous ie each element in array with take same amount of space in memory

In [ ]:
x = np.arange(0, 3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z], dtype = np.int16)
print(multi_array)
print(multi_array.shape)
print(multi_array.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
int16


In [ ]:
multi_array[1, 2]

5

In [ ]:
#50 represents the number of equally spaced points between 1 and 10
#If false value up to 10 not included
w = np.linspace(1, 10, 50, False)
print(w)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


In [ ]:
#3 represents stepsize
w = np.arange(1, 30, 3)

One Dimensional Slicing\
[start stop step]\
start: start index from where we want to start slicing (include value at start index)\
stop: index till where we would like to slice (exclude value at stop index)\
step: spacing in between the sequence of values


In [3]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [4]:
print(x[2:7])

[3 4 5 6 7]


Print every second number

In [5]:
print(x[2:7:2])

[3 5 7]


In [6]:
print(x[:7])

[1 2 3 4 5 6 7]


In [7]:
print(x[2:])

[3 4 5 6 7 8 9]


Reshaping

In [12]:
print(x.reshape(3, 3))
#this means that reshaping doesnt alter the original structure of x
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [16]:
print(x.reshape(-1, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(x.reshape(3, -1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
y = np.arange(18).reshape(2, 3, -1)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


Multidimensional Slicing

In [26]:
#accessing element from an array
print(y[1][2][0])

#slicing arrays
print(y[1])

15
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [28]:
print(y[1][:2][:2])

[[ 9 10 11]
 [12 13 14]]


In [29]:
print(y[1, ...])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [30]:
print(y[:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [38]:
print(y[:, 0, 0])
#:2 in the end with :3 is the step size, ie. pick every second element
print(y[:, :2, :3:2])

[0 9]
[[[ 0  2]
  [ 3  5]]

 [[ 9 11]
  [12 14]]]


Conditional Selection with Bools

In [40]:
comparison_op = y > 5
print(comparison_op)

[[[False False False]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [42]:
#return all elements that satisfy the conditional operation
y[comparison_op]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [43]:
#more elegant way of writing conditional operator
y[y > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [45]:
#max value
print(y.max())
#min value
print(y.min())

17
0


Manipulating array shapes

In [49]:
y1 = np.arange(9).reshape(3, 3)
print(y1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Flatten a multidimensional array using ravel and flatten\
Difference between ravel and flatten:\
ravel : returns view of the array being flattened\
flatten: creates a flattened copy of the array being flattened

In [53]:
ravelled_array = y1.ravel()
ravelled_array[2] = 1000
#here, change in ravelled array also gets reflected in the original array as 
#ravel does not create a copy but works on the original array
print(ravelled_array)
print(y1)

[   0    1 1000    3    4    5    6    7    8]
[[   0    1 1000]
 [   3    4    5]
 [   6    7    8]]


In [54]:
flattened_array = y1.flatten()
flattened_array[3] = 500
#here, modifying flattened array does not modify the original array as the oper-
#ation is performed on copy rather than the original
print(flattened_array)
print(y1)

[   0    1 1000  500    4    5    6    7    8]
[[   0    1 1000]
 [   3    4    5]
 [   6    7    8]]


In [58]:
y2 = np.arange(9)
y2.shape = [3, 3]
print(y2)
#transpose
print(y2.transpose())
#another method
print(y2.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [61]:
#if the resized size is bigger than the original size, the array is filled with 
#copies of element of original array
print(np.resize(y2, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [62]:
#default type is float64
np.zeros((6,))

array([0., 0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [65]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [66]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
#random samples from uniform distribution containing values from 0 to 1
np.random.rand(3, 3)

array([[0.35162434, 0.43693107, 0.36165005],
       [0.03087672, 0.5573476 , 0.52499195],
       [0.93440353, 0.067518  , 0.90056916]])

Matrix Multiplication

In [70]:
mat_A = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
mat_A

matrix([[0, 3, 5],
        [5, 5, 2]])

In [71]:
mat_B = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
mat_B

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [72]:
mat_A*mat_B

matrix([[ 29, -16],
        [ 38,   6]])

In [73]:
product = np.matmul(mat_A, mat_B)
product

matrix([[ 29, -16],
        [ 38,   6]])

In [74]:
mat_A @ mat_B

matrix([[ 29, -16],
        [ 38,   6]])

Stacking

In [109]:
#hstack : horizontal, columnwise sequence stacking
x_ = np.arange(4).reshape(2, 2)
print(x_)

[[0 1]
 [2 3]]


In [110]:
y_ = np.arange(4, 8).reshape(2, 2)
print(y_)

[[4 5]
 [6 7]]


In [111]:
#arrays being stacked should have same dims of elements along all expect the last
#axis. hstack concatenates along the second dimension
z_h = np.hstack((x_, y_))
print(z_h)

[[0 1 4 5]
 [2 3 6 7]]


In [112]:
#vtsack : vertical, rowwise sequence stacking
z_v = np.vstack((x_, y_))
print(z_v)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [113]:
#axis = 0, concatenation along vertical axis
#axis = 1, concatenation along horizontal axis
w_v = np.concatenate((x_, y_), axis = 0)
print(w_v)

w_h = np.concatenate((x_, y_), axis = 1)
print(w_h)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [114]:
#concatenation along axis = 1 and hstack are equivalent operations
print(z_h == w_h)

[[ True  True  True  True]
 [ True  True  True  True]]


In [92]:
#concatenation along axis = 0 and vstack are equivalent operations
#this also shows that arrays can be compared with ==
print(z_v == w_v)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


Depth stacking

In [115]:
#here, since x_ and y_ have a 2 x 2 shape, it intuitively adds a third dimension
#of size 1
x_1 = x_.reshape(2, 2, 1)
print(x_1)
y_1 = y_.reshape(2, 2, 1)
print(y_1)
depth_stack = np.dstack((x_1, y_1))
print(depth_stack)

[[[0]
  [1]]

 [[2]
  [3]]]
[[[4]
  [5]]

 [[6]
  [7]]]
[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [116]:
print(depth_stack.shape)

(2, 2, 2)


In [117]:
print(np.column_stack((x_, y_)))

[[0 1 4 5]
 [2 3 6 7]]


In [118]:
print(np.hstack((x_, y_)))

[[0 1 4 5]
 [2 3 6 7]]


In [119]:
print(np.column_stack((x_, y_)) == np.hstack((x_, y_)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [120]:
print(np.row_stack((x_, y_)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
